export type RankingCategory = 'popular' | 'rated' | 'favorite'

export interface RankedMovie {
  id: string
  title: string
  year: string
  genre: string
  rating: string
  metric: string
  posterColor: string
}

export interface MovieRanking {
  label: string
  shortLabel: string
  description: string
  movies: RankedMovie[]
}

export const movieRankingsData: Record<RankingCategory, MovieRanking> = {
  popular: {
    label: 'Most Popular',
    shortLabel: 'Popular',
    description: 'The 10 most watched movies in the community this week.',
    movies: [
      {
        id: 'heneral-luna-popular',
        title: 'Heneral Luna',
        year: '2015',
        genre: 'Historical',
        rating: '7.9',
        metric: '24.8K views',
        posterColor: 'from-red-950 via-amber-950 to-stone-900',
      },
      {
        id: 'four-sisters-popular',
        title: 'Four Sisters and a Wedding',
        year: '2013',
        genre: 'Comedy',
        rating: '7.3',
        metric: '21.3K views',
        posterColor: 'from-purple-950 via-violet-950 to-slate-900',
      },
      {
        id: 'kita-kita-popular',
        title: 'Kita Kita',
        year: '2017',
        genre: 'Romance',
        rating: '7.6',
        metric: '18.9K views',
        posterColor: 'from-fuchsia-950 via-pink-950 to-zinc-900',
      },
      {
        id: 'otj-popular',
        title: 'On the Job',
        year: '2013',
        genre: 'Thriller',
        rating: '7.0',
        metric: '16.7K views',
        posterColor: 'from-red-950 via-zinc-900 to-black',
      },
      {
        id: 'seven-sundays-popular',
        title: 'Seven Sundays',
        year: '2017',
        genre: 'Family',
        rating: '7.8',
        metric: '15.2K views',
        posterColor: 'from-amber-950 via-orange-950 to-stone-900',
      },
      {
        id: 'one-more-chance-popular',
        title: 'One More Chance',
        year: '2007',
        genre: 'Romance',
        rating: '7.7',
        metric: '14.6K views',
        posterColor: 'from-rose-950 via-pink-900 to-amber-950',
      },
      {
        id: 'goyo-popular',
        title: 'Goyo: Ang Batang Heneral',
        year: '2018',
        genre: 'Historical',
        rating: '7.5',
        metric: '13.9K views',
        posterColor: 'from-blue-950 via-slate-900 to-amber-950',
      },
      {
        id: 'tadhana-popular',
        title: 'That Thing Called Tadhana',
        year: '2014',
        genre: 'Romance',
        rating: '7.6',
        metric: '12.7K views',
        posterColor: 'from-pink-950 via-rose-950 to-zinc-900',
      },
      {
        id: 'buybust-popular',
        title: 'BuyBust',
        year: '2018',
        genre: 'Action',
        rating: '6.8',
        metric: '11.5K views',
        posterColor: 'from-cyan-950 via-slate-900 to-black',
      },
      {
        id: 'fan-girl-popular',
        title: 'Fan Girl',
        year: '2020',
        genre: 'Drama',
        rating: '7.2',
        metric: '10.8K views',
        posterColor: 'from-violet-950 via-purple-950 to-rose-950',
      },
    ],
  },
  rated: {
    label: 'Best Rated',
    shortLabel: 'Top Rated',
    description: 'The 10 highest scores from Filipino film fans.',
    movies: [
      {
        id: 'maynila-rated',
        title: 'Maynila sa mga Kuko ng Liwanag',
        year: '1975',
        genre: 'Crime',
        rating: '8.1',
        metric: '8.1 / 10',
        posterColor: 'from-amber-950 via-slate-900 to-indigo-950',
      },
      {
        id: 'himala-rated',
        title: 'Himala',
        year: '1982',
        genre: 'Drama',
        rating: '8.0',
        metric: '8.0 / 10',
        posterColor: 'from-rose-950 via-rose-900 to-amber-950',
      },
      {
        id: 'magnifico-rated',
        title: 'Magnifico',
        year: '2003',
        genre: 'Drama',
        rating: '8.0',
        metric: '8.0 / 10',
        posterColor: 'from-yellow-950 via-amber-900 to-zinc-950',
      },
      {
        id: 'bar-boys-rated',
        title: 'Bar Boys',
        year: '2017',
        genre: 'Drama',
        rating: '7.9',
        metric: '7.9 / 10',
        posterColor: 'from-indigo-950 via-blue-950 to-zinc-900',
      },
      {
        id: 'heneral-luna-rated',
        title: 'Heneral Luna',
        year: '2015',
        genre: 'Historical',
        rating: '7.9',
        metric: '7.9 / 10',
        posterColor: 'from-red-950 via-amber-950 to-stone-900',
      },
      {
        id: 'dekada-70-rated',
        title: "Dekada '70",
        year: '2002',
        genre: 'Drama',
        rating: '7.8',
        metric: '7.8 / 10',
        posterColor: 'from-stone-900 via-neutral-900 to-red-950',
      },
      {
        id: 'seven-sundays-rated',
        title: 'Seven Sundays',
        year: '2017',
        genre: 'Family',
        rating: '7.8',
        metric: '7.8 / 10',
        posterColor: 'from-amber-950 via-orange-950 to-stone-900',
      },
      {
        id: 'oro-plata-mata-rated',
        title: 'Oro, Plata, Mata',
        year: '1982',
        genre: 'War',
        rating: '7.7',
        metric: '7.7 / 10',
        posterColor: 'from-emerald-950 via-teal-950 to-stone-900',
      },
      {
        id: 'one-more-chance-rated',
        title: 'One More Chance',
        year: '2007',
        genre: 'Romance',
        rating: '7.7',
        metric: '7.7 / 10',
        posterColor: 'from-rose-950 via-pink-900 to-amber-950',
      },
      {
        id: 'kita-kita-rated',
        title: 'Kita Kita',
        year: '2017',
        genre: 'Romance',
        rating: '7.6',
        metric: '7.6 / 10',
        posterColor: 'from-fuchsia-950 via-pink-950 to-zinc-900',
      },
    ],
  },
  favorite: {
    label: 'Most Favorite',
    shortLabel: 'Favorites',
    description: 'The 10 movies saved most often to personal watchlists.',
    movies: [
      {
        id: 'one-more-chance-favorite',
        title: 'One More Chance',
        year: '2007',
        genre: 'Romance',
        rating: '7.7',
        metric: '12.4K saves',
        posterColor: 'from-rose-950 via-pink-900 to-amber-950',
      },
      {
        id: 'four-sisters-favorite',
        title: 'Four Sisters and a Wedding',
        year: '2013',
        genre: 'Comedy',
        rating: '7.3',
        metric: '11.8K saves',
        posterColor: 'from-purple-950 via-violet-950 to-slate-900',
      },
      {
        id: 'tadhana-favorite',
        title: 'That Thing Called Tadhana',
        year: '2014',
        genre: 'Romance',
        rating: '7.6',
        metric: '10.6K saves',
        posterColor: 'from-pink-950 via-rose-950 to-zinc-900',
      },
      {
        id: 'kita-kita-favorite',
        title: 'Kita Kita',
        year: '2017',
        genre: 'Romance',
        rating: '7.6',
        metric: '9.9K saves',
        posterColor: 'from-fuchsia-950 via-pink-950 to-zinc-900',
      },
      {
        id: 'seven-sundays-favorite',
        title: 'Seven Sundays',
        year: '2017',
        genre: 'Family',
        rating: '7.8',
        metric: '9.1K saves',
        posterColor: 'from-amber-950 via-orange-950 to-stone-900',
      },
      {
        id: 'heneral-luna-favorite',
        title: 'Heneral Luna',
        year: '2015',
        genre: 'Historical',
        rating: '7.9',
        metric: '8.7K saves',
        posterColor: 'from-red-950 via-amber-950 to-stone-900',
      },
      {
        id: 'bar-boys-favorite',
        title: 'Bar Boys',
        year: '2017',
        genre: 'Drama',
        rating: '7.9',
        metric: '8.2K saves',
        posterColor: 'from-indigo-950 via-blue-950 to-zinc-900',
      },
      {
        id: 'himala-favorite',
        title: 'Himala',
        year: '1982',
        genre: 'Drama',
        rating: '8.0',
        metric: '7.8K saves',
        posterColor: 'from-rose-950 via-rose-900 to-amber-950',
      },
      {
        id: 'magnifico-favorite',
        title: 'Magnifico',
        year: '2003',
        genre: 'Drama',
        rating: '8.0',
        metric: '7.3K saves',
        posterColor: 'from-yellow-950 via-amber-900 to-zinc-950',
      },
      {
        id: 'goyo-favorite',
        title: 'Goyo: Ang Batang Heneral',
        year: '2018',
        genre: 'Historical',
        rating: '7.5',
        metric: '6.9K saves',
        posterColor: 'from-blue-950 via-slate-900 to-amber-950',
      },
    ],
  },
}
